#!/bin/sh

LD_PRELOAD="/usr/lib/preloadable_libiconv.so"

# Populate database if not exists
test -f /data/htdocs/db/tm.sqlite || cp /data/htdocs/db_schema/tm.sqlite /data/htdocs/db/tm.sqlite
test -f /data/htdocs/db/config.xml || cp /data/htdocs/config.xml /data/htdocs/db/config.xml

# Configure system
source /usr/bin/update-configs.sh

# Set cron timeuot for engine.php
echo "${CRON_TIMEOUT} ${CRON_COMMAND}" > /etc/crontabs/nginx

# Force user/group ID
[ "q${PUID}" == "q" ] || usermod -o -u "$PUID" nginx
[ "q${PGID}" == "q" ] || groupmod -o -g "$PGID" nginx

# Set owner for app directory
chown -R nginx:nginx /data/htdocs
chown -R nginx:nginx /var/log/nginx

# Write temp files by nginx
chmod 777 /tmp

# Compatibility links
test -f /usr/bin/php-fpm || ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm
test -f /usr/bin/php || ln -s /usr/bin/php7 /usr/bin/php

# Start apps
crond
php-fpm
nginx -g 'daemon off;'
